### ISSUE TITLE
individual figures done, now trying to merge

### ISSUE THREAD

**Issue by zoekitchel** [pinskylab/ARMS_ClimateShift#2]
@mpinsky , wanted to let you know that the individual figures are done. Now working with Michelle for the best way to merge them.

Let me know if you'd like me to make any changes to individual figures at this point. Most updated ones in [figures folder](https://github.com/pinskylab/ARMS_ClimateShift/tree/master/draft_figures).

**Comment by mpinsky** [comment]
Amazing! These look fantastic. 

Totally small things to tweak:
- plot2: A bit more white space above "Focal range edge"
- plot2: Axis title text a bit bigger
- plot2: A bit more whitespace to the right and left of "Not Expanding | Expanding"
- plot3: Legend colors don't appear to match the data (?)

**Comment by zoekitchel** [comment]
plot2: A bit more white space above "Focal range edge" _done_
plot2: Axis title text a bit bigger _done_
plot2: A bit more whitespace to the right and left of "Not Expanding | Expanding" _done_
plot3: Legend colors don't appear to match the data (?) 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I have:
                             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  tempchange
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cooler /No change /Warmer
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Deeper           45         /      0          /         0
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; No change      0        /        51     /             0
       &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Shallower         0          /      0     /            10

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;which seems to line up with data? Happy to chat tomorrow.

**Comment by zoekitchel** [comment]
@mpinsky, I hit the point of diminishing returns in terms of finding a way to merge the plots in R, so I finished in powerpoint. Happy to make any changes that you see fit. [Here's the final as it stands now.](https://github.com/pinskylab/ARMS_ClimateShift/blob/master/draft_figures/fig3new_final.png)
